# https://opensearch.org/downloads.html
# http://localhost:5601 admin admin

version: '3'
services:
  node:
    image: opensearchproject/opensearch
    volumes:
      - ./data/data:/usr/share/opensearch/data
      # - ./data/config:/usr/share/opensearch/config
    ports:
      - 9200:9200
      # - 9600:9600 # Performance Analyzer
    environment:
      - node.name=node
      - discovery.seed_hosts=node
      - cluster.initial_master_nodes=node
      # - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - network

  dashboard:
    image: opensearchproject/opensearch-dashboards
    ports:
      - 5601:5601
    depends_on:
      - node
    environment:
      OPENSEARCH_HOSTS: '["https://node:9200"]'
    networks:
      - network

networks:
  network:
