version: '3'
services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 80:80
    links:
      - mongo
      - redis
    volumes:
      - ./data/sharelatex:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: Overleaf
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: true
      EMAIL_CONFIRMATION_DISABLED: true
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

  mongo:
    restart: always
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:5
    expose:
      - 6379
    volumes:
      - ./data/redis:/data
