# https://hub.docker.com/r/resilio/sync

version: 3

services:
  resilio:
    image: resilio/sync
    restart: always
    ports:
      - 8888:8888 # gui
      - 55555:55555
    volumes:
      - ./data:/mnt/sync
