# https://hub.docker.com/r/resilio/sync
# http://localhost:8888

version: '3'

services:
    resilio:
        image: resilio/sync
        restart: always
        ports:
            - 8888:8888
            - 55555:55555
        volumes:
            - ./data:/mnt/sync
