# https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml

version: '3'

services:
  rsshub:
    image: diygod/rsshub
    restart: always
    ports:
      - 1200:1200
    environment:
      NODE_ENV: production
