# https://github.com/owncloud/ocis
# http://localhost:9200

version: '3.7'

services:
  ocis:
    image: owncloud/ocis
    restart: always
    ports:
      - 9200:9200
    volumes:
      - ./data:/var/tmp/ocis
