# https://github.com/owncloud/ocis
# http://localhost:9200

services:
  ocis:
    image: owncloud/ocis
    restart: always
    ports:
      - 9200:9200
    environment:
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "true"
    volumes:
      - ./ocis.yaml:/etc/ocis/ocis.yaml
      - ocis-data:/var/lib/ocis
volumes:
  ocis-data:
