# https://miniflux.app/docs/installation.html#docker

version: '3'

services:
  miniflux:
    image: miniflux/miniflux
    restart: always
    ports:
      - 897:8080
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://root:password@postgres/postgres?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=root
      - ADMIN_PASSWORD=password
      
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
