# https://miniflux.app/docs/installation.html#docker
# http://localhost:897

version: '3'

services:
    miniflux:
        image: miniflux/miniflux
        restart: always
        ports:
            - 897:8080
        depends_on:
            - database
        environment:
            - DATABASE_URL=postgres://miniflux:password@database/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=root
            - ADMIN_PASSWORD=password

    database:
        image: postgres
        environment:
            - POSTGRES_USER=miniflux
            - POSTGRES_PASSWORD=password
        volumes:
            - database:/var/lib/postgresql/data

volumes:
    database:
