# https://www.home-assistant.io/installation/linux#install-home-assistant-container
# http://<host>:8123

version: '3'

services:
  homeassistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
