# https://www.home-assistant.io/installation/linux#install-home-assistant-container
# http://localhost:8123

version: '3'

services:
  homeassistant:
    image: homeassistant/home-assistant
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./data:/config
