# https://github.com/nextcloud/docker
# https://localhost:843

version: '3'

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 843:80
    volumes:
      - data:/var/www/html

volumes:
  data:
