# https://github.com/mxpv/podsync/blob/master/docker-compose.yml

version: '3'

services:
  podsync:
    image: mxpv/podsync
    restart: always
    ports:
      - 993:80
    volumes:
      - ./data/config.toml:/app/config.toml
      - ./data/data:/app/data
