# https://github.com/MariaDB/mariadb-docker

version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
