# https://github.com/syncthing/syncthing/blob/main/README-Docker.md
# http://localhost:8384

version: '3'

services:
    syncthing:
        image: syncthing/syncthing
        restart: always
        ports:
            - 8384:8384
            - 22000:22000
        volumes:
            - ./data:/var/syncthing
