# https://github.com/gogs/gogs/tree/main/docker

version: '3'

services:
    gogs:
        image: gogs/gogs
        restart: always
        ports:
            - 3000:3000 # gui
            - 1022:22
        volumes:
            - ./data:/data

volumes:
    data:
