# https://github.com/gogs/gogs/tree/main/docker
# https://localhost:10080

version: '3'

services:
  app:
    image: gogs/gogs
    restart: always
    ports:
      - 10080:3000
      - 10022:22
    volumes:
      - data:/data

volumes:
  data:
